# Generated by Django 3.2.7 on 2021-10-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='заголовок')),
                ('text', models.TextField(verbose_name='текст')),
                ('date', models.DateTimeField(verbose_name='дата')),
            ],
        ),
    ]
